Adding support to log tenantId
Safe-Security/logger pull request #17
Opened 2022-12-08 07:49 UTC by Substancia

Includes handling of missing contexts.

Evidences:-
MT with context: [https://app.flonnect.com/view/video/jibin.m/63919070f31aaa756ef77d3d](https://app.flonnect.com/view/video/jibin.m/63919070f31aaa756ef77d3d)
MT without context: [https://app.flonnect.com/view/video/jibin.m/63919100f31aaa756ef77d5f](https://app.flonnect.com/view/video/jibin.m/63919100f31aaa756ef77d5f)
ST: [https://app.flonnect.com/view/video/jibin.m/6391944cf31aaa756ef77df4](https://app.flonnect.com/view/video/jibin.m/6391944cf31aaa756ef77df4)

2022-12-08 08:00 UTC, amanjain14 commented on package.json
> +  "version": "1.2.2",
Revert this change. We have auto-release configured.

2022-12-08 08:01 UTC, amanjain14 commented on src/index.ts
> +                console.error(
Remove the error log.

2022-12-08 08:04 UTC, amanjain14 requested changes

2022-12-08 08:04 UTC, amanjain14 commented on src/index.ts
> +        info.tenantId = "";
Remove this as well. If we get tenantId from the context then use it, else make no changes.

2022-12-08 08:04 UTC, amanjain14 commented on src/index.ts
> +    return winston.format(info => {
Can we remove the dependency on the tenantId and make this generic?
From the parameters config, get the keys, check if the key is present in the store, if yes, add it to `info` else skip.

2022-12-08 08:06 UTC, amanjain14 commented on src/index.ts
> +    return winston.format(info => {
Please update the PR title with breaking changes.

2022-12-08 11:32 UTC, Substancia commented
To test this:-

New `createLogger` method call in `<container>/src/config/logger.ts` is
```
const logger = createLogger({
    logLevel: APP_LOG_LEVEL,
    service: process.env.SERVICE_NAME,
    config: {
        parameters: {
            tenantId: {
                valueFromMethod: getValueFromStore
            }
        }
    }
});
```

2022-12-13 11:07 UTC, aneeshrelan approved these changes
LGTM

2022-12-13 11:08 UTC, merged